[package]
name = "string_wizard"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "manipulate string like wizards"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
index_vec = { version = "0.1.3" }
rustc-hash = { version = "1.1.0" }
text-size = "1.1.1"
